In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# loading data 
Fraud_check = pd.read_csv("D:\\Random Forests assign 15\\Fraud_check.csv")
Fraud_check.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [3]:
Fraud_check.loc[Fraud_check['Taxable.Income'] <=30000,'Taxable_Income']= 'Risky'
Fraud_check.loc[Fraud_check['Taxable.Income'] >30000,'Taxable_Income']= 'Good'

In [4]:
Fraud_check.drop('Taxable.Income',1,inplace=True)

In [5]:
Fraud_check['Marital.Status'].value_counts()

Single      217
Married     194
Divorced    189
Name: Marital.Status, dtype: int64

In [6]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
Fraud_check['Marital.Status']= label_encoder.fit_transform(Fraud_check['Marital.Status']) 
Fraud_check['Marital.Status'].unique() 

array([2, 0, 1])

In [7]:
Fraud_check.Undergrad.value_counts()

YES    312
NO     288
Name: Undergrad, dtype: int64

In [8]:
Fraud_check['Undergrad']= label_encoder.fit_transform(Fraud_check['Undergrad']) 
Fraud_check['Undergrad'].unique() 

array([0, 1])

In [9]:
Fraud_check.Urban.value_counts()

YES    302
NO     298
Name: Urban, dtype: int64

In [10]:
Fraud_check['Urban']= label_encoder.fit_transform(Fraud_check['Urban']) 
Fraud_check['Urban'].unique() 

array([1, 0])

In [11]:
colnames = list(Fraud_check.columns)
predictors = colnames[0:5]
target = colnames[5]

In [12]:
predictors

['Undergrad', 'Marital.Status', 'City.Population', 'Work.Experience', 'Urban']

In [13]:
target

'Taxable_Income'

In [14]:
X = Fraud_check[predictors]
Y = Fraud_check[target]

In [15]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [16]:
Fraud_check['rf_pred'] = rf.predict(X)

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Fraud_check['Taxable_Income'],Fraud_check['rf_pred'])

array([[476,   0],
       [  0, 124]], dtype=int64)